crm/crm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lead.urls',namespace="lead")),
]

crm/lead/urls.py
from django.urls import path
from .import views



app_name = 'lead'
urlpatterns = [
    path('', views.homepage,name='home'),
    path('lead/', views.LeadListView.as_view(),name='lead'),
    path('<int:pk>/', views.LeadDetailView.as_view(),name='lead_details'),
    path('<int:pk>/update/', views.LeadUpdateView.as_view(),name='lead_update'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(),name='lead_delete'),
    path('create/', views.LeadCreateView.as_view(),name='lead_create'),
    path('no/', views.No.as_view(),name='no'),


    path('lead/search/', views.search_results,name='search_results'),
    path('sync/', views.lead,name='sync'),
    path('async/', views.lead_async,name='async'),
    

    
]

crm/lead/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

# Create your models here.

class User(AbstractUser):
    pass



class Lead(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey('Agent',on_delete=models.CASCADE)
    def __str__(self):
        return self.first_name

class LeadProfile(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(default=0)

class Agent(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username


def set_profile(sender,instance,created,**kwargs):
    #print(instance.last_name)
    if created:
        LeadProfile.objects.create(first_name=instance.first_name,last_name=instance.last_name,age=instance.age)


post_save.connect(set_profile,sender=Lead)

crm/lead/forms.py
from django.forms import ModelForm
from .models import Lead

class LeadForm(ModelForm):
    class Meta:
        model = Lead
        fields = '__all__'

#s LeadForm(forms.Form):
#first_name = forms.CharField#(max_length=50)
#last_name = forms.CharField#(max_length=50)
#age = forms.IntegerField#(min_value=0)

        

crm/lead/views.py
from django.http.response import JsonResponse
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Lead
from .forms import LeadForm
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView,TemplateView
from django.urls import reverse
from django.contrib.auth.mixins import PermissionRequiredMixin

from asgiref.sync import async_to_sync
import time



# Create your views here.

def homepage(request):
    return HttpResponse('hello homepage')

class LeadListView(ListView):
    model = Lead
    context_object_name = 'leads'

class LeadDetailView(DetailView):
    context_object_name = 'lead'
    queryset = Lead.objects.all()

class LeadCreateView(PermissionRequiredMixin,CreateView):
    permission_required = 'is_staff'
    template_name = 'lead/lead_create.html'
    form_class = LeadForm
    def handle_no_permission(self):
        return redirect('/no/')
    def get_success_url(self):
        return reverse("lead:lead")
class LeadUpdateView(UpdateView):
    template_name = 'lead/lead_update.html'
    queryset = Lead.objects.all()
    form_class = LeadForm
    def get_success_url(self):
        return reverse("lead:lead")

class No(TemplateView):
    template_name ='no.html'

class LeadDeleteView(DeleteView):
    template_name = 'lead/lead_delete.html'
    queryset = Lead.objects.all()
    form_class = LeadForm
    def get_success_url(self):
        return reverse("lead:lead")


# search value in request
def search_results(request):
    if request.is_ajax():
        res = None
        people = request.POST.get('people')
        #print('people')
        qs = Lead.objects.filter(first_name__icontains=people)
        #print(qs)
        if len(people)>0 and len(qs)>0:
            data = []
            for pos in qs:
                item = {
                    'pk':pos.pk,
                    'first_name':pos.first_name
                }
                data.append(item)
            res = data
        else:
            res = 'not found'
        return JsonResponse({'data':res})
    return JsonResponse({})


def lead(request):
    start_time = time.time()
    leads = Lead.objects.all()
    total = (time.time()-start_time)
    print(total)
    context = {
        'leads': leads
    }
    return render(request,'sync.html',context)

@async_to_sync
async def lead_async(request):
    start_time = time.time()
    leads = Lead.objects.all()
    total = (time.time()-start_time)
    print(total)
    context = {
        'leads': leads
    }
    return render(request,'async.html',context)


def lead_details(request,pk):
    lead = Lead.objects.get(id=pk)
    context = {'lead': lead }
    return render(request,'lead_details.html',context)

def lead_create(request):
    form = LeadForm()
    data =[]
    if request.is_ajax():
        form = LeadForm(request.POST)
        if form.is_valid():
            form.save()
    context = {
        'form':form
    }
    return render(request,'lead_create.html',context)

def lead_update(request,pk):
    lead = Lead.objects.get(id=pk)
    form = LeadForm(instance=lead)
    if request.method == 'POST':
        form = LeadForm(request.POST,instance=lead)
        if form.is_valid():
            form.save()
            return redirect('/lead')
    context = {
        'form':form,
        'lead':lead
    }
    return render(request,'lead_create.html',context)
def lead_delete(request,pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/lead')
    

crm/templates/async.html
<b>async</b>

crm/templates/lead/lead_create.html
{% load static %}

<html>
    <body>
       
        <b> <a href="{% url 'lead:lead' %}">previous page</a> </b>
        <hr>
        <b>
            Create a lead
        </b>
        
        <form method="post" id="p-form">
            {% csrf_token %}
            {{form.as_p }}
            <button id='submit' type="submit">Submit</button>
        </form>
        <div id='resultBox'>
            
        </div>
        
    </body>

    <script src="{% static 'form.js' %}" type="text/javascript"></script>
        
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</html>

crm/templates/lead/lead_delete.html
<html>
    <body>
        <b> <a href="{% url 'lead:lead' %}">previous page</a> </b>
        <hr>
        <b>
            Are you share Delete this lead 
        </b>
        
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
        
        
    </body>
</html>

crm/templates/lead/lead_detail.html
<html>
    <body>
        <b> <a href="{% url 'lead:lead' %}">previous page</a> </b>
        <hr>
        <p>
            {{ lead.first_name }}
            
        </p>
        <hr>
        <a href="{% url 'lead:lead_update' lead.pk %}">Update</a>
        <a href="{% url 'lead:lead_delete' lead.pk %}">Delete</a>
            
    </body>
</html>

crm/templates/lead/lead_list.html
{% load static %}

<html>
   <head>
       <link rel="stylesheet" href="{% static 'main.css' %}">
   </head>
    <body>
        <b>
            <a href="{% url 'lead:lead_create' %}">
                Create lead
            </a>
            
        </b>
        <form id="search-form" autocomplete="off" method="post">
            {% csrf_token %}
             <input type="text" id="search-input" placeholder="search">

        </form>
        <div class="result-card" id="result-box">

        </div>

        <hr>
        <p>
            {% for lead in leads %}

                <a href="{% url 'lead:lead_details' lead.pk %}">
                    {{ lead.first_name }} {{ lead.last_name }}
                </a>
                
                <small>{{ lead.age }}</small>
                <br>
                
            {% endfor %}
            
        </p>

        <script src="{% static 'main.js' %}" type="text/javascript"></script>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

        
    </body>
</html>

crm/templates/lead/lead_update.html
<html>
    <body>
        <b> <a href="{% url 'lead:lead' %}">previous page</a> </b>
        <hr>
        <b>
            update {{ lead.first_name }} {{lead.last_name}}
        </b>
        
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
        
        
    </body>
</html>

crm/templates/no.html
<html>
    <body>
      <b>No beach</b>
        
    </body>
</html>

crm/templates/sync.html
<b>sync</b>